language: emacs-lisp
git:
  # deactivate ci-travis's automatic dealing with submodules when cloning - http://docs.travis-ci.com/user/build-configuration/#Git-Submodules
  submodules: false
before_install:
  # to permit to change the git url to public ones
  - sed -e 's/git@github.com:/http:\/\/git@github.com\//g' -i .gitmodules
  - git submodule update --init
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - ls
  - pwd
  # - deploy emacs-live
  - git clone http://git@github.com/bbatsov/prelude.git ~/.emacs.d
  - echo "(let ((prelude-packs-file (expand-file-name \"~/.prelude-packs/prelude.el\"))) (when (file-exists-p prelude-packs-file) (load-file prelude-packs-file)))" > ~/.emacs.d/personal/init.el
  # - deploy prelude-packs
  - $(pwd)/deploy.sh
env:
  #- EMACS=emacs
  - EMACS=emacs24
  # - EMACS=emacs-snapshot
script:
  ./run-travis-ci.sh
