language: nix
git:
  # deactivate ci-travis's automatic dealing with submodules when
  # cloning -
  # http://docs.travis-ci.com/user/build-configuration/#Git-Submodules
  submodules: false
os: linux
before_script:
  # to permit to change the git url to public ones
  - sed -e 's/git@github.com:/http:\/\/github.com\//g' -i .gitmodules
  - git submodule update --init
  # install emacs from nix
  - git clone --depth=10 http://github.com/ardumont/dot-files ~/dot-files
  - rm -rf ~/.nixpkgs
  - ln -nsf ~/dot-files/.nixpkgs ~/.nixpkgs
  - ln -nsf ~/dot-files/nixos/emacs.nix ~/.nixpkgs/emacs.nix
  - pushd ~/.nixpkgs/
  - source ~/.nix-profile/etc/profile.d/nix.sh
  - nix-build emacs.nix
  - ./result/bin/emacs --version
  - popd
  # - deploy prelude
  - rm -rf ~/.emacs.d
  - git clone --depth=10 http://github.com/bbatsov/prelude.git ~/.emacs.d
  # - deploy prelude-packs
  - $(pwd)/deploy.sh
script:
  ~/.nixpkgs/result/bin/emacs --no-window-system --batch --load ~/.emacs.d/init.el
